print(" |\__/|")
print(" )    (")
print("=\    /=")
print("  )==(")
print(" /    \ ")
print(" |    |")
print("/      \ ")
print("\      /")
print(" \____/")
print("   ((")
print("    ))")
print("   ((")